/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.24.2
 * source: job/Job.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace job {
    export enum ResponseStatus {
        OK = 0,
        InternalErr = 1
    }
    export class FindJobRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            role?: number;
            byId?: number;
            index?: number;
            size?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("role" in data && data.role != undefined) {
                    this.role = data.role;
                }
                if ("byId" in data && data.byId != undefined) {
                    this.byId = data.byId;
                }
                if ("index" in data && data.index != undefined) {
                    this.index = data.index;
                }
                if ("size" in data && data.size != undefined) {
                    this.size = data.size;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get role() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set role(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get byId() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set byId(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get index() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set index(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get size() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set size(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            id?: number;
            role?: number;
            byId?: number;
            index?: number;
            size?: number;
        }): FindJobRequest {
            const message = new FindJobRequest({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.role != null) {
                message.role = data.role;
            }
            if (data.byId != null) {
                message.byId = data.byId;
            }
            if (data.index != null) {
                message.index = data.index;
            }
            if (data.size != null) {
                message.size = data.size;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                role?: number;
                byId?: number;
                index?: number;
                size?: number;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.role != null) {
                data.role = this.role;
            }
            if (this.byId != null) {
                data.byId = this.byId;
            }
            if (this.index != null) {
                data.index = this.index;
            }
            if (this.size != null) {
                data.size = this.size;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt32(1, this.id);
            if (this.role != 0)
                writer.writeInt32(2, this.role);
            if (this.byId != 0)
                writer.writeInt32(3, this.byId);
            if (this.index != 0)
                writer.writeInt32(4, this.index);
            if (this.size != 0)
                writer.writeInt32(5, this.size);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): FindJobRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new FindJobRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt32();
                        break;
                    case 2:
                        message.role = reader.readInt32();
                        break;
                    case 3:
                        message.byId = reader.readInt32();
                        break;
                    case 4:
                        message.index = reader.readInt32();
                        break;
                    case 5:
                        message.size = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): FindJobRequest {
            return FindJobRequest.deserialize(bytes);
        }
    }
    export class FindJobByNameRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            jobName?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("jobName" in data && data.jobName != undefined) {
                    this.jobName = data.jobName;
                }
            }
        }
        get jobName() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set jobName(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            jobName?: string;
        }): FindJobByNameRequest {
            const message = new FindJobByNameRequest({});
            if (data.jobName != null) {
                message.jobName = data.jobName;
            }
            return message;
        }
        toObject() {
            const data: {
                jobName?: string;
            } = {};
            if (this.jobName != null) {
                data.jobName = this.jobName;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.jobName.length)
                writer.writeString(1, this.jobName);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): FindJobByNameRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new FindJobByNameRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.jobName = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): FindJobByNameRequest {
            return FindJobByNameRequest.deserialize(bytes);
        }
    }
    export class FindJobByIdRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            jobId?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("jobId" in data && data.jobId != undefined) {
                    this.jobId = data.jobId;
                }
            }
        }
        get jobId() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set jobId(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            jobId?: string;
        }): FindJobByIdRequest {
            const message = new FindJobByIdRequest({});
            if (data.jobId != null) {
                message.jobId = data.jobId;
            }
            return message;
        }
        toObject() {
            const data: {
                jobId?: string;
            } = {};
            if (this.jobId != null) {
                data.jobId = this.jobId;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.jobId.length)
                writer.writeString(1, this.jobId);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): FindJobByIdRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new FindJobByIdRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.jobId = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): FindJobByIdRequest {
            return FindJobByIdRequest.deserialize(bytes);
        }
    }
    export class FindAllJobRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            index?: number;
            size?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("index" in data && data.index != undefined) {
                    this.index = data.index;
                }
                if ("size" in data && data.size != undefined) {
                    this.size = data.size;
                }
            }
        }
        get index() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set index(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get size() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set size(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            index?: number;
            size?: number;
        }): FindAllJobRequest {
            const message = new FindAllJobRequest({});
            if (data.index != null) {
                message.index = data.index;
            }
            if (data.size != null) {
                message.size = data.size;
            }
            return message;
        }
        toObject() {
            const data: {
                index?: number;
                size?: number;
            } = {};
            if (this.index != null) {
                data.index = this.index;
            }
            if (this.size != null) {
                data.size = this.size;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.index != 0)
                writer.writeInt32(1, this.index);
            if (this.size != 0)
                writer.writeInt32(2, this.size);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): FindAllJobRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new FindAllJobRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.index = reader.readInt32();
                        break;
                    case 2:
                        message.size = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): FindAllJobRequest {
            return FindAllJobRequest.deserialize(bytes);
        }
    }
    export class FindJobResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            header?: ResponseHeader;
            jobMsg?: JobMessage[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("header" in data && data.header != undefined) {
                    this.header = data.header;
                }
                if ("jobMsg" in data && data.jobMsg != undefined) {
                    this.jobMsg = data.jobMsg;
                }
            }
        }
        get header() {
            return pb_1.Message.getWrapperField(this, ResponseHeader, 1) as ResponseHeader;
        }
        set header(value: ResponseHeader) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_header() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get jobMsg() {
            return pb_1.Message.getRepeatedWrapperField(this, JobMessage, 2) as JobMessage[];
        }
        set jobMsg(value: JobMessage[]) {
            pb_1.Message.setRepeatedWrapperField(this, 2, value);
        }
        static fromObject(data: {
            header?: ReturnType<typeof ResponseHeader.prototype.toObject>;
            jobMsg?: ReturnType<typeof JobMessage.prototype.toObject>[];
        }): FindJobResponse {
            const message = new FindJobResponse({});
            if (data.header != null) {
                message.header = ResponseHeader.fromObject(data.header);
            }
            if (data.jobMsg != null) {
                message.jobMsg = data.jobMsg.map(item => JobMessage.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                header?: ReturnType<typeof ResponseHeader.prototype.toObject>;
                jobMsg?: ReturnType<typeof JobMessage.prototype.toObject>[];
            } = {};
            if (this.header != null) {
                data.header = this.header.toObject();
            }
            if (this.jobMsg != null) {
                data.jobMsg = this.jobMsg.map((item: JobMessage) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_header)
                writer.writeMessage(1, this.header, () => this.header.serialize(writer));
            if (this.jobMsg.length)
                writer.writeRepeatedMessage(2, this.jobMsg, (item: JobMessage) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): FindJobResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new FindJobResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.header, () => message.header = ResponseHeader.deserialize(reader));
                        break;
                    case 2:
                        reader.readMessage(message.jobMsg, () => pb_1.Message.addToRepeatedWrapperField(message, 2, JobMessage.deserialize(reader), JobMessage));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): FindJobResponse {
            return FindJobResponse.deserialize(bytes);
        }
    }
    export class SaveJobResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            header?: ResponseHeader;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("header" in data && data.header != undefined) {
                    this.header = data.header;
                }
            }
        }
        get header() {
            return pb_1.Message.getWrapperField(this, ResponseHeader, 1) as ResponseHeader;
        }
        set header(value: ResponseHeader) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_header() {
            return pb_1.Message.getField(this, 1) != null;
        }
        static fromObject(data: {
            header?: ReturnType<typeof ResponseHeader.prototype.toObject>;
        }): SaveJobResponse {
            const message = new SaveJobResponse({});
            if (data.header != null) {
                message.header = ResponseHeader.fromObject(data.header);
            }
            return message;
        }
        toObject() {
            const data: {
                header?: ReturnType<typeof ResponseHeader.prototype.toObject>;
            } = {};
            if (this.header != null) {
                data.header = this.header.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_header)
                writer.writeMessage(1, this.header, () => this.header.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SaveJobResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SaveJobResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.header, () => message.header = ResponseHeader.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): SaveJobResponse {
            return SaveJobResponse.deserialize(bytes);
        }
    }
    export class ResponseHeader extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            status?: ResponseStatus;
            message?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 1, ResponseStatus.OK) as ResponseStatus;
        }
        set status(value: ResponseStatus) {
            pb_1.Message.setField(this, 1, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            status?: ResponseStatus;
            message?: string;
        }): ResponseHeader {
            const message = new ResponseHeader({});
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            return message;
        }
        toObject() {
            const data: {
                status?: ResponseStatus;
                message?: string;
            } = {};
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.status != ResponseStatus.OK)
                writer.writeEnum(1, this.status);
            if (this.message.length)
                writer.writeString(2, this.message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ResponseHeader {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ResponseHeader();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.status = reader.readEnum();
                        break;
                    case 2:
                        message.message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ResponseHeader {
            return ResponseHeader.deserialize(bytes);
        }
    }
    export class RegisteredCompanyReq extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            company?: Company;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("company" in data && data.company != undefined) {
                    this.company = data.company;
                }
            }
        }
        get company() {
            return pb_1.Message.getWrapperField(this, Company, 1) as Company;
        }
        set company(value: Company) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_company() {
            return pb_1.Message.getField(this, 1) != null;
        }
        static fromObject(data: {
            company?: ReturnType<typeof Company.prototype.toObject>;
        }): RegisteredCompanyReq {
            const message = new RegisteredCompanyReq({});
            if (data.company != null) {
                message.company = Company.fromObject(data.company);
            }
            return message;
        }
        toObject() {
            const data: {
                company?: ReturnType<typeof Company.prototype.toObject>;
            } = {};
            if (this.company != null) {
                data.company = this.company.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_company)
                writer.writeMessage(1, this.company, () => this.company.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RegisteredCompanyReq {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RegisteredCompanyReq();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.company, () => message.company = Company.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): RegisteredCompanyReq {
            return RegisteredCompanyReq.deserialize(bytes);
        }
    }
    export class Company extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            companyName?: string;
            companyLocation?: string;
            isVip?: number;
            isCertified?: number;
            registerTime?: number;
            updateTime?: number;
            industry?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("companyName" in data && data.companyName != undefined) {
                    this.companyName = data.companyName;
                }
                if ("companyLocation" in data && data.companyLocation != undefined) {
                    this.companyLocation = data.companyLocation;
                }
                if ("isVip" in data && data.isVip != undefined) {
                    this.isVip = data.isVip;
                }
                if ("isCertified" in data && data.isCertified != undefined) {
                    this.isCertified = data.isCertified;
                }
                if ("registerTime" in data && data.registerTime != undefined) {
                    this.registerTime = data.registerTime;
                }
                if ("updateTime" in data && data.updateTime != undefined) {
                    this.updateTime = data.updateTime;
                }
                if ("industry" in data && data.industry != undefined) {
                    this.industry = data.industry;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get companyName() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set companyName(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get companyLocation() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set companyLocation(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get isVip() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set isVip(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get isCertified() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set isCertified(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        get registerTime() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set registerTime(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        get updateTime() {
            return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
        }
        set updateTime(value: number) {
            pb_1.Message.setField(this, 7, value);
        }
        get industry() {
            return pb_1.Message.getFieldWithDefault(this, 8, "") as string;
        }
        set industry(value: string) {
            pb_1.Message.setField(this, 8, value);
        }
        static fromObject(data: {
            id?: number;
            companyName?: string;
            companyLocation?: string;
            isVip?: number;
            isCertified?: number;
            registerTime?: number;
            updateTime?: number;
            industry?: string;
        }): Company {
            const message = new Company({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.companyName != null) {
                message.companyName = data.companyName;
            }
            if (data.companyLocation != null) {
                message.companyLocation = data.companyLocation;
            }
            if (data.isVip != null) {
                message.isVip = data.isVip;
            }
            if (data.isCertified != null) {
                message.isCertified = data.isCertified;
            }
            if (data.registerTime != null) {
                message.registerTime = data.registerTime;
            }
            if (data.updateTime != null) {
                message.updateTime = data.updateTime;
            }
            if (data.industry != null) {
                message.industry = data.industry;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                companyName?: string;
                companyLocation?: string;
                isVip?: number;
                isCertified?: number;
                registerTime?: number;
                updateTime?: number;
                industry?: string;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.companyName != null) {
                data.companyName = this.companyName;
            }
            if (this.companyLocation != null) {
                data.companyLocation = this.companyLocation;
            }
            if (this.isVip != null) {
                data.isVip = this.isVip;
            }
            if (this.isCertified != null) {
                data.isCertified = this.isCertified;
            }
            if (this.registerTime != null) {
                data.registerTime = this.registerTime;
            }
            if (this.updateTime != null) {
                data.updateTime = this.updateTime;
            }
            if (this.industry != null) {
                data.industry = this.industry;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt32(1, this.id);
            if (this.companyName.length)
                writer.writeString(2, this.companyName);
            if (this.companyLocation.length)
                writer.writeString(3, this.companyLocation);
            if (this.isVip != 0)
                writer.writeInt32(4, this.isVip);
            if (this.isCertified != 0)
                writer.writeInt32(5, this.isCertified);
            if (this.registerTime != 0)
                writer.writeInt64(6, this.registerTime);
            if (this.updateTime != 0)
                writer.writeInt64(7, this.updateTime);
            if (this.industry.length)
                writer.writeString(8, this.industry);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Company {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Company();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt32();
                        break;
                    case 2:
                        message.companyName = reader.readString();
                        break;
                    case 3:
                        message.companyLocation = reader.readString();
                        break;
                    case 4:
                        message.isVip = reader.readInt32();
                        break;
                    case 5:
                        message.isCertified = reader.readInt32();
                        break;
                    case 6:
                        message.registerTime = reader.readInt64();
                        break;
                    case 7:
                        message.updateTime = reader.readInt64();
                        break;
                    case 8:
                        message.industry = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Company {
            return Company.deserialize(bytes);
        }
    }
    export class BoundCompanyReq extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            id?: number;
        }): BoundCompanyReq {
            const message = new BoundCompanyReq({});
            if (data.id != null) {
                message.id = data.id;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt32(1, this.id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BoundCompanyReq {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BoundCompanyReq();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): BoundCompanyReq {
            return BoundCompanyReq.deserialize(bytes);
        }
    }
    export class VerifyCompanyReq extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            id?: number;
        }): VerifyCompanyReq {
            const message = new VerifyCompanyReq({});
            if (data.id != null) {
                message.id = data.id;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt32(1, this.id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): VerifyCompanyReq {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new VerifyCompanyReq();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): VerifyCompanyReq {
            return VerifyCompanyReq.deserialize(bytes);
        }
    }
    export class CommonResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            header?: ResponseHeader;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("header" in data && data.header != undefined) {
                    this.header = data.header;
                }
            }
        }
        get header() {
            return pb_1.Message.getWrapperField(this, ResponseHeader, 1) as ResponseHeader;
        }
        set header(value: ResponseHeader) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_header() {
            return pb_1.Message.getField(this, 1) != null;
        }
        static fromObject(data: {
            header?: ReturnType<typeof ResponseHeader.prototype.toObject>;
        }): CommonResponse {
            const message = new CommonResponse({});
            if (data.header != null) {
                message.header = ResponseHeader.fromObject(data.header);
            }
            return message;
        }
        toObject() {
            const data: {
                header?: ReturnType<typeof ResponseHeader.prototype.toObject>;
            } = {};
            if (this.header != null) {
                data.header = this.header.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_header)
                writer.writeMessage(1, this.header, () => this.header.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CommonResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CommonResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.header, () => message.header = ResponseHeader.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): CommonResponse {
            return CommonResponse.deserialize(bytes);
        }
    }
    export class JobMessage extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            jobId?: number;
            jobName?: string;
            jobMoney?: number;
            jobReq?: string;
            jobLocation?: string;
            companyId?: number;
            recruiterName?: string;
            recruiterPhone?: string;
            jobNeed?: number;
            recruiterId?: number;
            openTime?: number;
            jobTags?: string;
            updateTime?: number;
            industry?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("jobId" in data && data.jobId != undefined) {
                    this.jobId = data.jobId;
                }
                if ("jobName" in data && data.jobName != undefined) {
                    this.jobName = data.jobName;
                }
                if ("jobMoney" in data && data.jobMoney != undefined) {
                    this.jobMoney = data.jobMoney;
                }
                if ("jobReq" in data && data.jobReq != undefined) {
                    this.jobReq = data.jobReq;
                }
                if ("jobLocation" in data && data.jobLocation != undefined) {
                    this.jobLocation = data.jobLocation;
                }
                if ("companyId" in data && data.companyId != undefined) {
                    this.companyId = data.companyId;
                }
                if ("recruiterName" in data && data.recruiterName != undefined) {
                    this.recruiterName = data.recruiterName;
                }
                if ("recruiterPhone" in data && data.recruiterPhone != undefined) {
                    this.recruiterPhone = data.recruiterPhone;
                }
                if ("jobNeed" in data && data.jobNeed != undefined) {
                    this.jobNeed = data.jobNeed;
                }
                if ("recruiterId" in data && data.recruiterId != undefined) {
                    this.recruiterId = data.recruiterId;
                }
                if ("openTime" in data && data.openTime != undefined) {
                    this.openTime = data.openTime;
                }
                if ("jobTags" in data && data.jobTags != undefined) {
                    this.jobTags = data.jobTags;
                }
                if ("updateTime" in data && data.updateTime != undefined) {
                    this.updateTime = data.updateTime;
                }
                if ("industry" in data && data.industry != undefined) {
                    this.industry = data.industry;
                }
            }
        }
        get jobId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set jobId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get jobName() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set jobName(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get jobMoney() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set jobMoney(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get jobReq() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set jobReq(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get jobLocation() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set jobLocation(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get companyId() {
            return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
        }
        set companyId(value: number) {
            pb_1.Message.setField(this, 7, value);
        }
        get recruiterName() {
            return pb_1.Message.getFieldWithDefault(this, 8, "") as string;
        }
        set recruiterName(value: string) {
            pb_1.Message.setField(this, 8, value);
        }
        get recruiterPhone() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set recruiterPhone(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get jobNeed() {
            return pb_1.Message.getFieldWithDefault(this, 10, 0) as number;
        }
        set jobNeed(value: number) {
            pb_1.Message.setField(this, 10, value);
        }
        get recruiterId() {
            return pb_1.Message.getFieldWithDefault(this, 11, 0) as number;
        }
        set recruiterId(value: number) {
            pb_1.Message.setField(this, 11, value);
        }
        get openTime() {
            return pb_1.Message.getFieldWithDefault(this, 12, 0) as number;
        }
        set openTime(value: number) {
            pb_1.Message.setField(this, 12, value);
        }
        get jobTags() {
            return pb_1.Message.getFieldWithDefault(this, 13, "") as string;
        }
        set jobTags(value: string) {
            pb_1.Message.setField(this, 13, value);
        }
        get updateTime() {
            return pb_1.Message.getFieldWithDefault(this, 14, 0) as number;
        }
        set updateTime(value: number) {
            pb_1.Message.setField(this, 14, value);
        }
        get industry() {
            return pb_1.Message.getFieldWithDefault(this, 15, "") as string;
        }
        set industry(value: string) {
            pb_1.Message.setField(this, 15, value);
        }
        static fromObject(data: {
            jobId?: number;
            jobName?: string;
            jobMoney?: number;
            jobReq?: string;
            jobLocation?: string;
            companyId?: number;
            recruiterName?: string;
            recruiterPhone?: string;
            jobNeed?: number;
            recruiterId?: number;
            openTime?: number;
            jobTags?: string;
            updateTime?: number;
            industry?: string;
        }): JobMessage {
            const message = new JobMessage({});
            if (data.jobId != null) {
                message.jobId = data.jobId;
            }
            if (data.jobName != null) {
                message.jobName = data.jobName;
            }
            if (data.jobMoney != null) {
                message.jobMoney = data.jobMoney;
            }
            if (data.jobReq != null) {
                message.jobReq = data.jobReq;
            }
            if (data.jobLocation != null) {
                message.jobLocation = data.jobLocation;
            }
            if (data.companyId != null) {
                message.companyId = data.companyId;
            }
            if (data.recruiterName != null) {
                message.recruiterName = data.recruiterName;
            }
            if (data.recruiterPhone != null) {
                message.recruiterPhone = data.recruiterPhone;
            }
            if (data.jobNeed != null) {
                message.jobNeed = data.jobNeed;
            }
            if (data.recruiterId != null) {
                message.recruiterId = data.recruiterId;
            }
            if (data.openTime != null) {
                message.openTime = data.openTime;
            }
            if (data.jobTags != null) {
                message.jobTags = data.jobTags;
            }
            if (data.updateTime != null) {
                message.updateTime = data.updateTime;
            }
            if (data.industry != null) {
                message.industry = data.industry;
            }
            return message;
        }
        toObject() {
            const data: {
                jobId?: number;
                jobName?: string;
                jobMoney?: number;
                jobReq?: string;
                jobLocation?: string;
                companyId?: number;
                recruiterName?: string;
                recruiterPhone?: string;
                jobNeed?: number;
                recruiterId?: number;
                openTime?: number;
                jobTags?: string;
                updateTime?: number;
                industry?: string;
            } = {};
            if (this.jobId != null) {
                data.jobId = this.jobId;
            }
            if (this.jobName != null) {
                data.jobName = this.jobName;
            }
            if (this.jobMoney != null) {
                data.jobMoney = this.jobMoney;
            }
            if (this.jobReq != null) {
                data.jobReq = this.jobReq;
            }
            if (this.jobLocation != null) {
                data.jobLocation = this.jobLocation;
            }
            if (this.companyId != null) {
                data.companyId = this.companyId;
            }
            if (this.recruiterName != null) {
                data.recruiterName = this.recruiterName;
            }
            if (this.recruiterPhone != null) {
                data.recruiterPhone = this.recruiterPhone;
            }
            if (this.jobNeed != null) {
                data.jobNeed = this.jobNeed;
            }
            if (this.recruiterId != null) {
                data.recruiterId = this.recruiterId;
            }
            if (this.openTime != null) {
                data.openTime = this.openTime;
            }
            if (this.jobTags != null) {
                data.jobTags = this.jobTags;
            }
            if (this.updateTime != null) {
                data.updateTime = this.updateTime;
            }
            if (this.industry != null) {
                data.industry = this.industry;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.jobId != 0)
                writer.writeInt32(2, this.jobId);
            if (this.jobName.length)
                writer.writeString(3, this.jobName);
            if (this.jobMoney != 0)
                writer.writeInt32(4, this.jobMoney);
            if (this.jobReq.length)
                writer.writeString(5, this.jobReq);
            if (this.jobLocation.length)
                writer.writeString(6, this.jobLocation);
            if (this.companyId != 0)
                writer.writeInt32(7, this.companyId);
            if (this.recruiterName.length)
                writer.writeString(8, this.recruiterName);
            if (this.recruiterPhone.length)
                writer.writeString(9, this.recruiterPhone);
            if (this.jobNeed != 0)
                writer.writeInt32(10, this.jobNeed);
            if (this.recruiterId != 0)
                writer.writeInt32(11, this.recruiterId);
            if (this.openTime != 0)
                writer.writeInt64(12, this.openTime);
            if (this.jobTags.length)
                writer.writeString(13, this.jobTags);
            if (this.updateTime != 0)
                writer.writeInt64(14, this.updateTime);
            if (this.industry.length)
                writer.writeString(15, this.industry);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): JobMessage {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new JobMessage();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 2:
                        message.jobId = reader.readInt32();
                        break;
                    case 3:
                        message.jobName = reader.readString();
                        break;
                    case 4:
                        message.jobMoney = reader.readInt32();
                        break;
                    case 5:
                        message.jobReq = reader.readString();
                        break;
                    case 6:
                        message.jobLocation = reader.readString();
                        break;
                    case 7:
                        message.companyId = reader.readInt32();
                        break;
                    case 8:
                        message.recruiterName = reader.readString();
                        break;
                    case 9:
                        message.recruiterPhone = reader.readString();
                        break;
                    case 10:
                        message.jobNeed = reader.readInt32();
                        break;
                    case 11:
                        message.recruiterId = reader.readInt32();
                        break;
                    case 12:
                        message.openTime = reader.readInt64();
                        break;
                    case 13:
                        message.jobTags = reader.readString();
                        break;
                    case 14:
                        message.updateTime = reader.readInt64();
                        break;
                    case 15:
                        message.industry = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): JobMessage {
            return JobMessage.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedJobService {
        static definition = {
            FindAllJobs: {
                path: "/job.Job/FindAllJobs",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: FindAllJobRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => FindAllJobRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: FindJobResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => FindJobResponse.deserialize(new Uint8Array(bytes))
            },
            FindJobByName: {
                path: "/job.Job/FindJobByName",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: FindJobByNameRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => FindJobByNameRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: FindJobResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => FindJobResponse.deserialize(new Uint8Array(bytes))
            },
            FindJobById: {
                path: "/job.Job/FindJobById",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: FindJobByIdRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => FindJobByIdRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: FindJobResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => FindJobResponse.deserialize(new Uint8Array(bytes))
            },
            FindJobs: {
                path: "/job.Job/FindJobs",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: FindJobRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => FindJobRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: FindJobResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => FindJobResponse.deserialize(new Uint8Array(bytes))
            },
            SaveJobs: {
                path: "/job.Job/SaveJobs",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: JobMessage) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => JobMessage.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: SaveJobResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => SaveJobResponse.deserialize(new Uint8Array(bytes))
            },
            UpdateJobs: {
                path: "/job.Job/UpdateJobs",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: JobMessage) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => JobMessage.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: SaveJobResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => SaveJobResponse.deserialize(new Uint8Array(bytes))
            },
            RegisteredCompany: {
                path: "/job.Job/RegisteredCompany",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: RegisteredCompanyReq) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => RegisteredCompanyReq.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: CommonResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => CommonResponse.deserialize(new Uint8Array(bytes))
            },
            UpdateCompany: {
                path: "/job.Job/UpdateCompany",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: RegisteredCompanyReq) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => RegisteredCompanyReq.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: CommonResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => CommonResponse.deserialize(new Uint8Array(bytes))
            },
            BoundCompany: {
                path: "/job.Job/BoundCompany",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: BoundCompanyReq) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => BoundCompanyReq.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: CommonResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => CommonResponse.deserialize(new Uint8Array(bytes))
            },
            VerifyCompany: {
                path: "/job.Job/VerifyCompany",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: VerifyCompanyReq) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => VerifyCompanyReq.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: CommonResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => CommonResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract FindAllJobs(call: grpc_1.ServerUnaryCall<FindAllJobRequest, FindJobResponse>, callback: grpc_1.sendUnaryData<FindJobResponse>): void;
        abstract FindJobByName(call: grpc_1.ServerUnaryCall<FindJobByNameRequest, FindJobResponse>, callback: grpc_1.sendUnaryData<FindJobResponse>): void;
        abstract FindJobById(call: grpc_1.ServerUnaryCall<FindJobByIdRequest, FindJobResponse>, callback: grpc_1.sendUnaryData<FindJobResponse>): void;
        abstract FindJobs(call: grpc_1.ServerUnaryCall<FindJobRequest, FindJobResponse>, callback: grpc_1.sendUnaryData<FindJobResponse>): void;
        abstract SaveJobs(call: grpc_1.ServerUnaryCall<JobMessage, SaveJobResponse>, callback: grpc_1.sendUnaryData<SaveJobResponse>): void;
        abstract UpdateJobs(call: grpc_1.ServerUnaryCall<JobMessage, SaveJobResponse>, callback: grpc_1.sendUnaryData<SaveJobResponse>): void;
        abstract RegisteredCompany(call: grpc_1.ServerUnaryCall<RegisteredCompanyReq, CommonResponse>, callback: grpc_1.sendUnaryData<CommonResponse>): void;
        abstract UpdateCompany(call: grpc_1.ServerUnaryCall<RegisteredCompanyReq, CommonResponse>, callback: grpc_1.sendUnaryData<CommonResponse>): void;
        abstract BoundCompany(call: grpc_1.ServerUnaryCall<BoundCompanyReq, CommonResponse>, callback: grpc_1.sendUnaryData<CommonResponse>): void;
        abstract VerifyCompany(call: grpc_1.ServerUnaryCall<VerifyCompanyReq, CommonResponse>, callback: grpc_1.sendUnaryData<CommonResponse>): void;
    }
    export class JobClient extends grpc_1.makeGenericClientConstructor(UnimplementedJobService.definition, "Job", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        FindAllJobs: GrpcUnaryServiceInterface<FindAllJobRequest, FindJobResponse> = (message: FindAllJobRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<FindJobResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<FindJobResponse>, callback?: grpc_1.requestCallback<FindJobResponse>): grpc_1.ClientUnaryCall => {
            return super.FindAllJobs(message, metadata, options, callback);
        };
        FindJobByName: GrpcUnaryServiceInterface<FindJobByNameRequest, FindJobResponse> = (message: FindJobByNameRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<FindJobResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<FindJobResponse>, callback?: grpc_1.requestCallback<FindJobResponse>): grpc_1.ClientUnaryCall => {
            return super.FindJobByName(message, metadata, options, callback);
        };
        FindJobById: GrpcUnaryServiceInterface<FindJobByIdRequest, FindJobResponse> = (message: FindJobByIdRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<FindJobResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<FindJobResponse>, callback?: grpc_1.requestCallback<FindJobResponse>): grpc_1.ClientUnaryCall => {
            return super.FindJobById(message, metadata, options, callback);
        };
        FindJobs: GrpcUnaryServiceInterface<FindJobRequest, FindJobResponse> = (message: FindJobRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<FindJobResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<FindJobResponse>, callback?: grpc_1.requestCallback<FindJobResponse>): grpc_1.ClientUnaryCall => {
            return super.FindJobs(message, metadata, options, callback);
        };
        SaveJobs: GrpcUnaryServiceInterface<JobMessage, SaveJobResponse> = (message: JobMessage, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<SaveJobResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<SaveJobResponse>, callback?: grpc_1.requestCallback<SaveJobResponse>): grpc_1.ClientUnaryCall => {
            return super.SaveJobs(message, metadata, options, callback);
        };
        UpdateJobs: GrpcUnaryServiceInterface<JobMessage, SaveJobResponse> = (message: JobMessage, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<SaveJobResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<SaveJobResponse>, callback?: grpc_1.requestCallback<SaveJobResponse>): grpc_1.ClientUnaryCall => {
            return super.UpdateJobs(message, metadata, options, callback);
        };
        RegisteredCompany: GrpcUnaryServiceInterface<RegisteredCompanyReq, CommonResponse> = (message: RegisteredCompanyReq, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<CommonResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<CommonResponse>, callback?: grpc_1.requestCallback<CommonResponse>): grpc_1.ClientUnaryCall => {
            return super.RegisteredCompany(message, metadata, options, callback);
        };
        UpdateCompany: GrpcUnaryServiceInterface<RegisteredCompanyReq, CommonResponse> = (message: RegisteredCompanyReq, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<CommonResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<CommonResponse>, callback?: grpc_1.requestCallback<CommonResponse>): grpc_1.ClientUnaryCall => {
            return super.UpdateCompany(message, metadata, options, callback);
        };
        BoundCompany: GrpcUnaryServiceInterface<BoundCompanyReq, CommonResponse> = (message: BoundCompanyReq, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<CommonResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<CommonResponse>, callback?: grpc_1.requestCallback<CommonResponse>): grpc_1.ClientUnaryCall => {
            return super.BoundCompany(message, metadata, options, callback);
        };
        VerifyCompany: GrpcUnaryServiceInterface<VerifyCompanyReq, CommonResponse> = (message: VerifyCompanyReq, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<CommonResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<CommonResponse>, callback?: grpc_1.requestCallback<CommonResponse>): grpc_1.ClientUnaryCall => {
            return super.VerifyCompany(message, metadata, options, callback);
        };
    }
}
